### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by innocenzi** [lepikhinb/momentum-modal#1]
Hey,

So I tried this out this morning since I'm implementing a modal in our app, but I had no luck making it work. 

Using the following routes:

```php
Route::inertia('/', 'index')->name('index');
Route::get('/passengers', function () {
    return Inertia::dialog('passengers.test')->with([
        'passengers' => [1, 2, 3],
    ])->baseRoute('index');
});
```

When visiting `/passengers` manually (non-Inertia request), I have ~~hundreds of~~ a "Session store not set on request." exception triggering because I use the session in my `HandleInertiaRequests` middleware:

**EDIT**: the "hundreds of" is because I had a custom exception handler using Inertia. Removing it solved the issue.

```php
 'notifications' => fn (Request $request) => [
      'success' => $request->session()->get('success'),
      // ...
  ],
```

If I remove that piece of code, I have a single exception in the base Inertia controller:

![image](https://user-images.githubusercontent.com/16060559/176167132-4527a396-485e-4097-b577-2c4b0362f058.png)

---

So I think there are two issues there:
- The request don't use my `web` middleware (I think?) since the session isn't started
- Using `Route::inertia` doesn't work with how the modal rendering logic is implemented

I can't set up a reproduction right now (don't have enough time), I think the second issue is easy to reproduce, not sure about the first though.

**Comment by lepikhinb** [comment]
This 23008a8912cefac20ac229c28f8d0b851cd3b60d should fix both issues.

**Comment by innocenzi** [comment]
Looks like this works! Thanks a lot. I'll be using this in a modal-heavy app and I'll report any shortcomings. Good work @lepikhinb 👍
