### ISSUE TITLE
syntax error, unexpected token ")"

### ISSUE THREAD

**Issue by syahrilanwar** [lepikhinb/momentum-modal#12]
Hi! 

i have simple form, but when i access route, I get an error in this section 

`
    {

        /** @var \Illuminate\Routing\Router */

        $router = app('router');

 

        $middleware = new SubstituteBindings($router);

 

        return $middleware->handle(

            $request,

            $route->run(...)

        );

    }

**Comment by lepikhinb** [comment]
Hey,

Update to the latest version of the package. The issue has been resolved with #8
