### ISSUE TITLE
Consider moving the npm package into the same repo

### ISSUE THREAD

**Issue by Tofandel** [lepikhinb/momentum-modal#16]
To avoid unexpected version mismatch, better VCS control and easier PRs consider moving the npm package repo into this repository and unpublishing the package

Then to install the plugin, the command would simply be `npm i vendor/based/momentum-modal/vue-3`

You could even do that automatically when the composer package is installed

**Comment by lepikhinb** [comment]
Thanks for the suggestion. I'll consider that for the first major version.
