### ISSUE TITLE
Cannot run Inertia SSR server

### ISSUE THREAD

**Issue by boris-glumpler** [lepikhinb/momentum-modal#17]
Hello,

thanks for this package!

I've been having issues running the SSR server (Inertia & Vite) with `momentum-modal`. It compiles just fine with `vite build --ssr`, but when I run it with `node bootstrap/ssr/ssr.mjs` I get the following error:

```
SyntaxError: Named export 'modal' not found. The requested module 'momentum-modal' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'momentum-modal';
const { modal } = pkg;
```

When I then make these changes in `ssr.ts` I get the following error:

```
node_modules/momentum-modal/dist/momentum-modal.es.js:1
import { ref, computed, shallowRef, watch, defineAsyncComponent, h, nextTick, defineComponent } from "vue";

SyntaxError: Cannot use import statement outside a module
```

The actual app runs just fine, btw. It's just SSR. Any help would be greatly appreciated!

**Comment by lepikhinb** [comment]
Please check the [example app](https://github.com/lepikhinb/momentum-modal-example/blob/master/resources/js/ssr.ts), it's using SSR and is compiling with no issues.

Anyway, I'm not sure that async components are renderable on the server side.

**Comment by boris-glumpler** [comment]
I can confirm that lepikhinb/momentum-modal-plugin#5 solves my issue.
