### ISSUE TITLE
TransitionRoot animation skipped when navigating

### ISSUE THREAD

**Issue by sebastiaanluca** [lepikhinb/momentum-modal#2]
A thing I noticed with Inertia, Headless UI, and using `TransitionRoot` is that it will skip the configured transition (or end it early) when navigating to or away from the modal route. Had a similar experience with a custom implementation. Kind of depends on how fast the route loads. When navigating to, it usually just pops up without transition. When navigating away, it starts but abruptly hides the modal when halfway.

I assumed `@after-leave="redirect"` would take care of this because it only starts navigating after the transition ended, but it doesn't.

Is there a way to fix this or configure it differently so it would fully transition in and out when navigating routes?

**Comment by lepikhinb** [comment]
For the opening transition, you need to set the `appear` property to make the transition work on an initial request.

Please check the [example](https://github.com/lepikhinb/momentum-modal-example/blob/master/resources/js/Shared/Modal.vue) implementation.

**Comment by sebastiaanluca** [comment]
I have that set (I used the modal and edit view from the examples), but because the page loads too fast, it skips it entirely or halfway.

```
<TransitionRoot appear as="template" :show="show" @after-leave="redirect">
    …
```

Either `@after-leave="redirect"` triggers too fast (duration set to 500ms using `duration-500`) or it ignores it and navigates instantly.

**Comment by sebastiaanluca** [comment]
That works like a charm! Sorry for the ticket 😅 And thanks for the package!

For those interested, the related tickets:
- https://github.com/tailwindlabs/headlessui/issues/1607
- https://github.com/tailwindlabs/headlessui/issues/1364
- https://github.com/tailwindlabs/headlessui/issues/1088

**Comment by lepikhinb** [comment]
It’s all good! Thank you for testing it out

**Comment by lepikhinb** [comment]
@sebastiaanluca also, I'd recommend putting the `@after-leave` event on a single `TransitionChild` instead of `TransitionRoot`, as it seems, that the root component fires the event for every transition child.
