### ISSUE TITLE
Page title cannot be set from modal

### ISSUE THREAD

**Issue by rvanbaalen** [lepikhinb/momentum-modal#20]
The title of a page cannot be modified when visiting a "modal"-page.

When I add this to a regular page, it works:

```vue
<Head title="Modal - List - App name />
```

when I add it to a modal page, nothing happens.

**Comment by lepikhinb** [comment]
Please check the [example](https://github.com/lepikhinb/momentum-modal-example/blob/master/resources/js/Pages/Contacts/Edit.vue). This should work as expected.

**Comment by rvanbaalen** [comment]
Sorry to bother you, it was an error on my side.
