### ISSUE TITLE
cannot figure how to set the package in a Breeze project.

### ISSUE THREAD

**Issue by ArielMejiaDev** [lepikhinb/momentum-modal#22]
Exception:

![Screen Shot 2022-08-18 at 9 18 37 AM](https://user-images.githubusercontent.com/31971074/185439548-8e416ff5-0651-41d8-8962-c6f9c3ec5d15.png)

Steps:

- Create new project
- Install Breeze with Vue
- Run migrations
- Install momentum-modal composer package
- Install momentum-modal npm package
- Install the Axios version supported for the package
- Set the changes on `resource/js/app.js` as the package requires
- Add a modal component `resources/js/Components/Modal.vue`
- Add the momentum modal component to the Layout `resources/js/Layouts/ApplicationLayout.vue`
- Then add a controller that points to a vue component with modal `app/Http/Controllers/UsersController@create`
- Create the modal vue component `resources/js/Pages/Users/CreateModal/vue`
- Set in the custom vue component the modal, importing your custom model and use it as a slot.

Here the project (is public): https://github.com/ArielMejiaDev/modal-tester

**Comment by lepikhinb** [comment]
The issue is not related to the package. The compiler can't reach the base `Modal` component. Check the [screenshot](https://share.cleanshot.com/zMSHLZ).

With Vite, you need to reference components explicitly with the extension: 
```diff
-import Modal from "@/Components/Modal";
+import Modal from "@/Components/Modal.vue";
```

I hope this helps 🙏🏻

**Comment by ArielMejiaDev** [comment]
I made the changes but I do not know why it is still returning the same exception it is pretty rare

**Comment by lepikhinb** [comment]
@ArielMejiaDev did you manage to solve the issue? I'm still confident it's unrelated to the package.

**Comment by ArielMejiaDev** [comment]
@lepikhinb I made the change that you suggest by adding `.vue` extension file, but it does not work

**Comment by fira03079508** [comment]
I'm having the same issue (started with a Breeze installation)
![image](https://user-images.githubusercontent.com/1340932/193430363-b6e77780-16b9-4adf-9995-338fec99a52c.png)
