### ISSUE TITLE
Modal component not loaded after login

### ISSUE THREAD

**Issue by svenvanhees** [lepikhinb/momentum-modal#26]
When navigating to the modal url, without an authenticated session, the modal component is not loaded. Instead the login page is still showing. This happens also on the PingCrm example.

Steps to reproduce.
Go to https://modal.advanced-inertia.com/contacts/86/edit
Login with credentials provided.

We have need of a way to link directly to the modal from an email for example.

To bypass this we have implemented the Modal.php our self and commented out the following line.

```
    protected function redirectURL(): string
    {
        if (request()->header('X-Inertia-Modal-Redirect')) {
            /** @phpstan-ignore-next-line */
            return request()->header('X-Inertia-Modal-Redirect');
        }

        $referer = request()->headers->get('referer');

//        if (request()->header('X-Inertia') && $referer && $referer != url()->current()) {
//            return $referer;
//        }

        return $this->baseURL;
    }
```

**Comment by vpuentem** [comment]
same issue here

**Comment by lepikhinb** [comment]
Working on it! Thanks
