### ISSUE TITLE
Redirecting from one modal to another

### ISSUE THREAD

**Issue by grantholle** [lepikhinb/momentum-modal#27]
I've got two modals that share the same base url/route. In one modal, I'm making doing a `form.put()`, where the redirect should be a new modal.

It's currently sending the right redirect response from the first (as far as I can tell), and _is_ `GET` calling the correct url of the second modal, but then it immediately `GET`s the base url.

<img width="1293" alt="Screen Shot 2022-09-26 at 11 38 43 AM" src="https://user-images.githubusercontent.com/1189456/192220213-6ccf2b3a-e6b4-4413-9fea-06ce1161ce0e.png">

**Comment by grantholle** [comment]
In my `PUT` action, if I return `Inertia::location($mySecondModalUrl)` it does load the second modal page without immediately going to the base url. Not ideal, but it achieves the functionality.

**Comment by lepikhinb** [comment]
IMO you should stick to 1 route = 1 modal, since that's the point of the package.

**Comment by grantholle** [comment]
Do you mean 1 route = 1 base url? Because my modals are on different routes.

**Comment by grantholle** [comment]
Or one modal per base route is more accurate.

My modals are on different routes, but they all share the same base url.

**Comment by lepikhinb** [comment]
Ah, I probably misread the message. I'm going to investigate the issue soon. It would help a lot if you can set up a reproduction repository.

**Comment by grantholle** [comment]
Sure, I will try recreate it

**Comment by lumore** [comment]
Can confirm.
Reproduction repo: https://github.com/lumore/momentum-modal-navigation-issue-example

**Comment by fira03079508** [comment]
I'm having a very similar issue. I have a link instead a modal that go to the "forgot password" modal 
![image](https://user-images.githubusercontent.com/1340932/193430668-a755f972-127a-4050-8699-d1b65ea69b99.png)

If I click on the forgot password link, the route redirects to the right route. But It doesn't do anything. If I click a second time: The forgot password modal loads :

![image](https://user-images.githubusercontent.com/1340932/193430693-34cc093e-40ac-4528-837a-e5291696fbfd.png)

**Comment by wPatrick** [comment]
I have encountered the same problem. In my case, the "X-Inertia-Modal-*" headers were not set. So it is clearly an axios problem. After I corrected the axios version as suggested in the installation instructions, it worked. 

I think this can be closed but maybe the documentation could address this clearly.

**Comment by emargareten** [comment]
👀

**Comment by lumore** [comment]
You should use the same version of axios as Inertia uses, that's written in docs. This should fix the problem.

`Warning The package utilizes axios under the hood. If your app is already using axios as a dependency, make sure to lock it to the same version Inertia uses.

`npm i axios@0.21.4``

**Comment by grantholle** [comment]
@lumore Not if you use an alias as mentioned in my [previous comment](https://github.com/lepikhinb/momentum-modal/issues/27#issuecomment-1280791739).

I encountered an issue with Axios interceptors as discussed [here](https://github.com/inertiajs/inertia/discussions/1241), and if correctly alias Axios, it resolves the issue.

**Comment by lepikhinb** [comment]
@lumore thanks for the clarification

@grantholle feel free to re-open the issue if the problem persists

The package has just been updated to support Inertia.js v.1.0. Make sure to update to the latest version.
