### ISSUE TITLE
Modal key change on request validation

### ISSUE THREAD

**Issue by dacoto97** [lepikhinb/momentum-modal#3]
X-Inertia-Modal-Key it is not being added to the headers

| GET(200) | PUT (303) | GET (200, validation error) | 
|-----|-----|-----|
|  ![CleanShot 2022-06-29 at 12 42 28@2x](https://user-images.githubusercontent.com/16915053/176418001-e4237480-fe8a-4e8d-8c2c-deca8cd95a52.png)   |   ![CleanShot 2022-06-29 at 12 43 43@2x](https://user-images.githubusercontent.com/16915053/176418229-99957de8-e28c-473f-a630-ff71cd333b60.png)  |   ![CleanShot 2022-06-29 at 12 44 29@2x](https://user-images.githubusercontent.com/16915053/176418405-26d6068b-ec71-4764-8c02-6b2785ae03bb.png)  | 

Some code:
|app.ts| Layout.vue | Modal.vue |
|-----|-----|-----|
| <img width="876" alt="CleanShot 2022-06-29 at 12 48 21@2x" src="https://user-images.githubusercontent.com/16915053/176419043-d422ff72-2c5c-4c7e-bc69-f63e7f2508cc.png"> | <img width="548" alt="image" src="https://user-images.githubusercontent.com/16915053/176419259-a4140999-9a02-4f7d-9618-b0b98ff51f61.png"> | <img width="642" alt="CleanShot 2022-06-29 at 12 51 48@2x" src="https://user-images.githubusercontent.com/16915053/176419660-d5c066fc-90ae-42a0-b421-761f698ae6e1.png"> |

**Comment by lepikhinb** [comment]
Can confirm the issue, just encountered that with the latest **axios** update as well. Will notify on the update.

**Comment by lepikhinb** [comment]
See #4
