### ISSUE TITLE
Vue 2

### ISSUE THREAD

**Issue by wrtisans** [lepikhinb/momentum-modal#30]
is there a reason to work only on vue 3 ? i've a proyect with vuetify and vue 2 and i would like to use this awesome package .. it's possible to make a PR to add support for vue 2 ?

**Comment by lepikhinb** [comment]
Vue 2 is reaching EOL the next year. There’s no reason to not upgrade to Vue 3 now

**Comment by wrtisans** [comment]
i know but currently im using vuetify and today only works with vue 2 ... please see [here]("https://next.vuetifyjs.com/en/introduction/roadmap/")

**Comment by wrtisans** [comment]
[here](https://next.vuetifyjs.com/en/introduction/roadmap/)

**Comment by lepikhinb** [comment]
Feel free to use the backend package and create an adapter for Vue 2. I guess, it’s doable with the Composition API dependency.

**Comment by wrtisans** [comment]
i will try, thanks a lot and congrats for this awesome package!
