### ISSUE TITLE
Feature Requests: Make Momentum Modal Available for Inertiajs React

### ISSUE THREAD

**Issue by andrewdwallo** [lepikhinb/momentum-modal#31]
It would be great if I could use this with React instead of Vue.. Simply because Reactjs offers many more 3rd Party API's and services. Just a thought. Thanks!

**Comment by lepikhinb** [comment]
There's a custom React implementation: https://gist.github.com/mxmtsk/cd01b0a3e43d21a51e054b1a92255092

I don't work with React, but would love it if someone could implement an adapter and do a PR.
