### ISSUE TITLE
Old base component shown when navigating to route with modal

### ISSUE THREAD

**Issue by rico** [lepikhinb/momentum-modal#33]
I'm having a weird issue when navigating (using `Inertia.get`) to an URL with a Modal - the modal is displayed properly, but the _base_ component is the one I navigated away from instead of the one defined as `baseRoute` for the modal. 

How can that be?

No, I really don't think it is an axios version problem, I only have one :-)

```
 npm list axios
code@ /Users/rico/smartcode/projects/smartprax/aarepraxis/code
├─┬ @inertiajs/inertia@0.11.1
│ └── axios@0.21.4 deduped
└── axios@0.21.4
```

**Comment by cristophergv** [comment]
Hello, did you manage to solve the issue?, the same thing happens to me.

**Comment by rico** [comment]
@cristophergv unfortunately not.

**Comment by lepikhinb** [comment]
@rico `Inertia.get` acts the same as the `Link` click, so it works as expected. I might try to implement some "force" param.

**Comment by rico** [comment]
@lepikhinb to be honest, I don't understand why this is expected. Definitely not what I expect :-)

What exactly would a `force` param do? And what do you suggest I do to get the base component to update - `Inertia::location()` or even full page reloads using `<a>`?

Thanks!
