### ISSUE TITLE
Use current page as baseRoute

### ISSUE THREAD

**Issue by MaticSulc** [lepikhinb/momentum-modal#37]
Hi,

would it be possible to use the current page as a default baseRoute?
Example: I have a simple CRUD app, and the same base form in my create and edit pages. 
Would it be possible to just automatically determine from where the request came from and use that as a backdrop?
Second thing, is there an option to not modify the URL at all? I've managed to partially implement it using redirect (from vue's useModal) , but it makes a redirect.

**Comment by jeffreyvanhees** [comment]
You will always have to define a base route, because the model is also always directly approachable via it's URL. I think what you want is not possible.

**Comment by lepikhinb** [comment]
@MaticSulc this is the way it currently works. For internal requests, it's using the previous route as a backdrop.

**Comment by MtDalPizzol** [comment]
Not sure... But if I don't call the `->baseRoute()` method on the controller, I get a `Typed property Momentum\Modal\Modal::$baseURL must not be accessed before initialization` error. Was expecting it to use the previous URL...
