### ISSUE TITLE
Example App default credentials aren't working

### ISSUE THREAD

**Issue by Pedro-Mag** [lepikhinb/momentum-modal#39]
When trying to access example app, the default credentials (johndoe@example.com/secret) don't grant access...

https://modal.advanced-inertia.com/login

![image](https://user-images.githubusercontent.com/74468488/209807179-15d3cb98-ea57-4aff-9922-7b5ccc5d62b6.png)

**Comment by SDIjeremy** [comment]
Having the same issue!
