### ISSUE TITLE
 Cannot read properties of null (reading 'props')

### ISSUE THREAD

**Issue by EfrenColin** [lepikhinb/momentum-modal#49]
I was working with laravel 10 dev, but now that it was released, updated and now when compiling with npm run dev with vite, it shows me this message  **Cannot read properties of null (reading 'props')**
![error](https://user-images.githubusercontent.com/46972740/218855169-e995dbaf-717d-458e-bd81-f5d0f7aa43b3.png)
![debug](https://user-images.githubusercontent.com/46972740/218855294-3570c786-4341-4f5a-b74e-96def85f9dc1.png)

**vite v4.1.1
laravel v10.0.0 plugin v0.7.4**

**Comment by JasperTey** [comment]
I also encountered this earlier today, but narrowed it down to the `@inertiajs/vue3` 1.0.1 release: https://github.com/inertiajs/inertia/releases/tag/v1.0.1

Locking `@inertiajs/vue3` to 1.0.0 in package.json was the temporary solution, for now.

**Comment by lepikhinb** [comment]
This should work well now with v0.2.1.

`npm install momentum-modal@latest`

Let me know if the issue persists.

**Comment by boring-dragon** [comment]
I am also getting the following exception. Tried with new version as well

**Comment by EfrenColin** [comment]
I updated the dependency and it worked correctly, thank you very much, great job
