### ISSUE TITLE
Modal resets form fields

### ISSUE THREAD

**Issue by bolivir** [lepikhinb/momentum-modal#5]
Im new with inertia and currently trying your package to implement the modal functionality.
Currently i can open the modal and perform a save action. If the save action gives a validation error the modal seems to flicker and resets the form fields values but shows the validation message. 

Any idea where i should start looking at why this behaviour occurs? This does not occur in your example and works fine there.

**Comment by lepikhinb** [comment]
Apparently, there's some issue related to Axios update. Please try downgrading it to v0.21.1

```bash
npm i axios@0.21.1
```

**Comment by lepikhinb** [comment]
Also, make sure to update both *npm* and *composer* dependencies of the Modal package to the latest versions.

**Comment by bolivir** [comment]
Will try asap thank you for the response

**Comment by bolivir** [comment]
I dont know why, but running npm update and composer update fixed it!

**Comment by lepikhinb** [comment]
Awesome, thanks!

**Comment by guilheb** [comment]
I'm having the same problem with the following versions, which I believe are the latest as of right now:

**composer.lock**
- based/momentum-modal: v0.1.6
- inertiajs/inertia-laravel: v0.6.3

**package-lock.json**
- axios: 0.27.2
- momentum-modal: 0.1.11
- @inertiajs/inertia: 0.11.0
- @inertiajs/inertia-vue3: 0.6.0

I have tried to install axios 0.21.1 and 0.21.4 but it didn't seem to fix the problem.

**Comment by mansoorkhan96** [comment]
Hi @lepikhinb 
I am using axios: `^1.2.0` and i have similar problem. It would reload the slide-over page and errors would not appear.
