### ISSUE TITLE
Parameters for base url are passed

### ISSUE THREAD

**Issue by GuidoHendriks** [lepikhinb/momentum-modal#7]
I'll start by saying how much I appreciate this package, I really like how it's working. Been adding it to one of my projects today and it's pretty magical. 👍🏻 

There seems to be a bug however. I spend quite a while looking into it but can't figure out what the best way to solve this would be. The problem occurs when the base route has parameters. It seems to reuse the parameters from the current route (= the modal route).

In my use case I have an edit form in a model. The base route is the `index` page with a month paramater. It's similar to this:
```php
public function index(?string $month) {
    // This shows an overview, a list of all months or just the specified month
}

public function edit(Project $project) {
    return Inertia::modal('Project/Show')
        ->with([
            'project' => $project,
        ])
        ->baseRoute('projects.index', $project->month);
}
```

Instead of using the `month` from `$project`, it passes the resolved parameters from `edit`. This happens on this line: https://github.com/lepikhinb/momentum-modal/blob/master/src/Modal.php#L76. In the tests it seems to work, but that because the parameters of the original route and the base route are matching, in this method for example: https://github.com/lepikhinb/momentum-modal/blob/master/tests/Stubs/ExampleController.php#L17-L24

In my specific case I could fix the issue by replacing `Route::current()?->parameters() ?? []` with `$baseRoute->parameters()`. But this way it just uses the value and does resolve any model bindings. Did spend quite some time trying to get the parameters to resolve, so I could create PR instead of an issue, but I ran out of time for this today.

Also found it does use the query data from the original route for the base route, not sure if that's by design? I can't think of a use case where that would be useful. This happens on this line: https://github.com/lepikhinb/momentum-modal/blob/master/src/Modal.php#L58

Hopefully this makes sense, let me know if you need more info or a sample project.

**Comment by GuidoHendriks** [comment]
Okay I went ahead and reproduced it in a [sample project](https://github.com/gigplanner/laravel-vilt) I recently created.

Migrate the database with seed, then login as `test@example.com` / `password`. Then go to "Posts", click one of the user names. Then notice you only see their posts, then when you click "Edit" the modal opens and suddenly all posts are shown. That's because of the issue mentioned above.

**Comment by lepikhinb** [comment]
Thank you for the reproduction! I'm aware of the issue, and will try to resolve it soon.

Meanwhile, feel free to do a PR if you know the solution.

**Comment by lepikhinb** [comment]
The recent commit c622892 should fix the issue. Please try updating to **v0.1.5**.

Let me know if this worked.

**Comment by GuidoHendriks** [comment]
This did solve the issue, thanks a lot! Feel kinda ashamed I didn't think about using the middleware. 🙈

**Comment by GuidoHendriks** [comment]
> Also found it does use the query data from the original route for the base route, not sure if that's by design? I can't think of a use case where that would be useful. This happens on this line: https://github.com/lepikhinb/momentum-modal/blob/master/src/Modal.php#L58

@lepikhinb Did you see this part? Noticed it's still in there, are query parameters from original request included by design?

**Comment by lepikhinb** [comment]
Yeah, it's by design to preserve page / query meta data. Check the example [here](https://modal.advanced-inertia.com/contacts?page=6) or [here](https://modal.advanced-inertia.com/contacts?search=emm), the background context remains the same without jumping to the first page.
