### ISSUE TITLE
Endless loop by accessing the model via its route

### ISSUE THREAD

**Issue by jeffreyvanhees** [lepikhinb/momentum-modal#9]
Hi @lepikhinb,

First of all, thanks for your package! It's feels like a Christmas present! 😄 

There is something going on that I can't explain. When I access the modal directly through its URL, the page hangs and eventually gives a ` Maximum execution time of 60 seconds exceeded`. I use the following code in the `showLoginForm()`-action in my default Laravel `LoginController` which is accessible by `/login`:

```php
public function showLoginForm()
{
    return Inertia::modal('auth/Login')
        ->baseRoute('web.login');
}
```

Now I am debugging a bit and the following code seems to cause an endless loop: 

https://github.com/lepikhinb/momentum-modal/blob/3bbd16bf4a4a80bd66be78b21dfbd173cfdad6c5/src/Modal.php#L124

```php
public function toResponse($request)
{
    $response = $this->render();

    if ($response instanceof Responsable) {
        return $response->toResponse($request);
    }

    return $response;
}
```

Maybe you can explain what makes this happen?

Jeffrey

**Comment by lepikhinb** [comment]
Hi Jeffrey,

Make sure you use a correct `baseRoute` — it should be a "background" context which the modal usually opens from. 

It should not be the same as the modal's route.

**Comment by jeffreyvanhees** [comment]
Thanks for your quick response! Indeed, this was the cause. Didn't noticed this at all. I guess I was staring at my screen too long :/
